### ISSUE TITLE
Attack quand il n'y a personne à attaquer

### ISSUE THREAD

**Issue by dbaelde** [GL-MPRI-2014/Ocawai#157]
Les feature requests ne sont peut être pas la priorité mais au cas où: Quand je fais attack et qu'il n'y a personne à portée d'attaque, cela effectue un déplacement et termine le tour de l'unité. C'est énervant quand on ne sait pas quelle est la portée de l'unité et qu'on fait attack pour tester. Je dirais que dans ce cas cela devrait échouer, et laisser le jouer faire un move à la place si c'est son intention. Ou alors j'ai mal compris le mode d'emploi?

PS: y a-t-il un moyen de voir la portée d'attaque sans tester ainsi?

**Comment by iSheeft** [comment]
De quoi parles-tu ?
https://github.com/GL-MPRI-2014/GL_MPRI_2014/search?utf8=%E2%9C%93&q=create_battle_menu
Si je fais la recherche, je ne trouve rien. (Tu peux aussi essayer `git grep create_battle_menu` si tu n'es pas convaincu).
