### ISSUE TITLE
Masquer le bouton menu pendant une sélection

### ISSUE THREAD

**Issue by TheoWinterhalter** [GL-MPRI-2014/Ocawai#181]
Actuellement, on peut ouvrir le menu un peu n'importe quand et surtout pendant le déplacement d'une unité. Ce qui permet ensuite de passer le tour et d'obtenir éventuellement une belle erreur !

J'ai voulu le faire à coup de `main_button#toggle` mais `main_button` n'est pas accessible dans la classe de `Game`. J'ai préféré ne pas tout mettre à sac dans le module pour une si petite modification.
Qu'en penses-tu @VLanvin ?

**Comment by VLanvin** [comment]
C'est fixé dans la branche amaze. J'ai ajouté une fonction pour changer le callback après la création de l'objet, je ne sais pas pourquoi je ne l'ai pas fait avant... Du coup, plus besoin du key_button_oneuse, et on peut faire un peu ce qu'on veut.
Actuellement, je bloque l'ouverture du menu si on est en train de déplacer une unité.
