### ISSUE TITLE
Soutenance

### ISSUE THREAD

**Issue by Saroupille** [GL-MPRI-2014/Ocawai#209]
J'ai crée sur la branche soutenance un dossier contenant un beamer. Il faudra qu'on se décide sur le thème utilisé.

Afin d'éviter qu'on se gène les uns les autres, je pense qu'il serait intéressant pour chaque section de la présentation d'avoir un fichier .tex à lui tout seul que l'on ajoute par la commande \include . Ca peut éviter un certains nombres de merge.

**Comment by VLanvin** [comment]
A-t-on déjà prévu de diviser la soutenance d'une manière particulière ? Sinon, je propose le partitionnement canonique : moteur(logique)/interface/musique/réseau/script.

Côté interface, je pense qu'il serait bien qu'on fasse tourner le jeu tout en parlant, ça illustrerait mieux ce dont on parle qu'un beamer. 
En revanche, pour ce qui est du script, je pense préparer un beamer avec les objectifs, la structure globale du langage, l'interaction avec Ocaml, et où @iSheeft pourra éventuellement rajouter le typechecker si il est motivé :)

**Comment by iSheeft** [comment]
Pour l'interface je suis d'accord !
Pour le type checker je verrais ce que tu as fait, mais je sais pas trop ce que je peux dire dessus.

**Comment by dbaelde** [comment]
Je rappelle les indications données par Nathan: la soutenance doit
expliquer quel était le projet, et présenter une démo, mais les discussions
ensuite doivent traiter des aspects GL. Cela n'exclut pas forcément d'avoir
le jeu derrière à l'écran, mais cela ne me parait pas être un choix évident.

On Wed, Jan 14, 2015 at 1:50 PM, Théo Winterhalter <notifications@github.com
> wrote:

> Pour l'interface je suis d'accord !
> Pour le type checker je verrais ce que tu as fait, mais je sais pas trop
> ce que je peux dire dessus.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GL-MPRI-2014/GL_MPRI_2014/issues/209#issuecomment-69911482>
> .
>



-- 
David

**Comment by iSheeft** [comment]
Oui j'imagine que pour l'interface, on peut parler des choses suivantes :

* Le *State Manager*
* Les *mixins*

En fait je vois pas quoi d'autre est digne d'intérêt d'un point de vue génie logiciel.
Les boutons `X` et `W` parce qu'ils utilisent des continuations ? :p

**Comment by VLanvin** [comment]
Ouep je suis d'accord avec les deux points. En fait, j'imaginais un beamer basique et le jeu en même temps, notamment pour illustrer avec du visuel le state manager par exemple, mais ce n'est pas vraiment possible...
A la limite j'ai aussi fait quelques optims avec les histoires de GPU, mais je pense qu'on a assez à dire.

**Comment by tbazin** [comment]
On se retrouve cet après-midi/en début de soirée pour en discuter ?
En 411 vers 18:30 ?

**Comment by iSheeft** [comment]
Oui tu peux parler de ça @VLanvin je pense…
@tbazin je ne pourrais pas tout de suite à cause du rendez-vous avec Dietmar.
Il commence à 18h, et je ne sais pas jusqu'à quand.

**Comment by VLanvin** [comment]
Je vais avoir du mal à venir je pense, ça me fait perdre presque 1h en trajet, et je suis vraiment à la bourre en catégories (je ne pige pas grand chose). Il y a moyen de s'arranger par IRC ?

**Comment by Saroupille** [comment]
Il y a aura une ou deux slides sur la partie intégration tests/makefile etc...

Probablement aussi que Julien va parler de l'interface client/moteur du côté des players.

Après si on s'arrange par IRC, si quelqu'un pouvait choisir un serveur et un canal...

**Comment by Saroupille** [comment]
Ya des slides qui ont commencé à se faire ? On oublie la branche soutenance ? Comment on s'organise ?

**Comment by VLanvin** [comment]
C'est ce que j'ai essayé de savoir, pas de réponse. 
Tu as déjà fait quelque chose ? Si oui, à la limite on peut t'envoyer les différentes parties et tu te charges de merger/include.

**Comment by Saroupille** [comment]
Je n'ai rien fait encore mais je comptais m'y mettre ce soir. Mais envoie je vais essayer de voir ça ;)

**Comment by Saroupille** [comment]
J'ai reçu que des slides de la part de Victor. Demain la sountenance, vous la fête en mode YOLO ?
