### ISSUE TITLE
Typeur trop laxiste

### ISSUE THREAD

**Issue by dbaelde** [GL-MPRI-2014/Ocawai#213]
Le typeur ne gère pas bien la récursion. Sur le code suivant il infère que la fonction attend une paire avec un entier en première composante, et `any_type` en seconde composante, ce qui est incorrect.

```scala
fun loop1 x = {
  var n = (fst x) + 1;
  loop1 (snd x);
}

// BUG: types but goes wrong
var foo = loop1 (1,"toto");
```

Au fond cet exemple pose la question de l'existence d'un `t` tel que `t = int*t`. Si on autorise un tel type infini alors la fonction `loop1` est permise -- et c'est possible, car elle ne termine pas mais respecte le typage. Sinon, une vérification d'occurs-check devrait faire échouer l'unification lors de la tentative de typage de `loop1`.

J'avoue ne pas avoir assez creusé le problème pour comprendre comment le `any_type` se retrouve là. Ce n'est pas un scénario auquel je m'attendais.

**Comment by iSheeft** [comment]
J'imagine que je n'ai pas accordé au typeur l'attention qu'il méritait…
J'en suis désolé. J'aurais du partir sur Hindley-Milner plutôt que sur un truc aussi simpliste j'imagine.

Et bien évidemment ajouter des test.

**Comment by iSheeft** [comment]
J'ai rapidement commencé à mettre en place des tests, mais je suis pas trop sûr encore de comment faire pour effectuer des tests plus généraux que ceux vérifiant que le tout type.
Dans l'idéal il ne faudrait pas avoir à modifier le code du type checker (pour les tests j'entends).

En revanche, est-ce que je devrais envisager de repartir de zéro sur un Hindley-Milner ou est-ce que je tente plutôt de corriger l'*Occurs Check*, sachant que j'ai peut-être d'autre problèmes…
(Je précise que je n'ai jamais prétendu traiter ce cas, mais c'est vrai que c'est dommage car "well-typed programs *may* go wrong").

**Comment by tbazin** [comment]
L'article aurait tout de suite eu moins d'impact si son titre avait été celui que tu donnes :)
________________________________
De : Théo Winterhalter<mailto:notifications@github.com>
Envoyé : ‎23/‎01/‎2015 19:43
À : GL-MPRI-2014/Ocawai<mailto:Ocawai@noreply.github.com>
Objet : Re: [Ocawai] Typeur trop laxiste (#213)

J'ai rapidement commencé à mettre en place des tests, mais je suis pas trop sûr encore de comment faire pour effectuer des tests plus généraux que ceux vérifiant que le tout type.
Dans l'idéal il ne faudrait pas avoir à modifier le code du type checker (pour les tests j'entends).

En revanche, est-ce que je devrais envisager de repartir de zéro sur un Hindley-Milner ou est-ce que je tente plutôt de corriger l'*Occurs Check*, sachant que j'ai peut-être d'autre problèmes…
(Je précise que je n'ai jamais prétendu traiter ce cas, mais c'est vrai que c'est dommage car "well-typed programs *may* go wrong").

---

**Comment by iSheeft** [comment]
En fait, j'avais tout faux ! C'est une mauvaise gestion des fonctions récursives ici (d'où la `any_type` qui semble sortir de nulle part), ça a l'air de se corriger simplement, mais je vais d'abord faire des tests pour être sûr de ne rien casser.

**Comment by iSheeft** [comment]
En fait j'ai parlé trop vite, le problème que j'ai cru voir n'est pas présent, et il s'agit bien d'*occurs check*.

```ocaml
unify t (int * t)
```

J'essaie de réparer ça…

**Comment by iSheeft** [comment]
Bon je m'en sors pas pour le moment…
En faisant des tests depuis l'interpréteur j'ai l'impression d'avoir le bon comportement pour vérifier l'occurs check. Mais le test (qui est celui de @dbaelde recopié) type toujours…

Le dernier commit a60e01dba6aa6aeabbaf0efcbf5c38d77cf5c1ef (dans une branch à part bien sûr) correspond à là où j'en suis arrivé. Je vais faire une pause.

**Comment by dbaelde** [comment]
Juste un petit message pour dire qu'à mon avis l'archi générale du typeur n'est pas à remettre en question. Même dans l'optique de gérer plus tard le polymorphisme à la Hindley-Milner, cela devrait pouvoir bien s'adapter sans tout reprendre de zéro. Pour les problèmes du moment, as-tu essayé un test qui repose sur l'occurs-check et pas la récursion? (Par exemple, `fun x -> x = fst x`.)

**Comment by iSheeft** [comment]
Je sais pas trop pourquoi mais maintenant j'ai bien le occurs check  quand il faut, mais aussi à un moment où il ne faut pas…

```bash
Error in test/script_test_assoc.script, from line 9:111 to line 9:111: One of the types ((any_type -> any_type -> unit) * ((any_type -> any_type) -> (unit -> any_type) -> any_type -> any_type)) and ((any_type -> any_type -> unit) * ((any_type -> any_type) -> (unit -> any_type) -> any_type -> any_type)) occurs in the other
```

Par ailleurs, `any_type` ne désigne pas n'importe quel type (contrairement à ce que son nom semble indiquer), mais une variable de type qui a peut-être déjà été unifiée sans avoir pour l'instant été spécifiée.
Peut-être que je pourrais mettre en évidence les liaisons avec du Oo.id ?

**Comment by iSheeft** [comment]
Okay, le bug actuel concerne deux types qui sont égaux.
Je n'ai plus qu'à faire attention à ce cas particulier et ça devrait aller. (Et puis maintenant on a des tests).
Je m'en occupe dès que je suis sur mon ordi (c'est une note pour moi même surtout, désolé).

**Comment by iSheeft** [comment]
Normalement, c'est corrigé, au lieu de vérifier l'égalité de deux types avant l'unification, je vérifie maintenant qu'ils représentent le même type (ce qui veut dire qu'avant cela il y avait un problème si on unifiait deux fois t et t').
