### ISSUE TITLE
Problème avec `assoc_t` ?

### ISSUE THREAD

**Issue by iSheeft** [GL-MPRI-2014/Ocawai#216]
On dirait que j'ai cassé *master* avec mon *occurs check* et mes modifications du *type checker*.

J'ai cependant du mal à comprendre l'erreur…
Le *type checker* donne une erreur de typage qui est réelle :
```bash
Error in ./resources/scripts/olive.script, from line 159:3851 to line 159:3851: function assoc_get of type (('a0 -> 'a1 -> unit) * (('a1 -> 'a2) -> (unit -> 'a2) -> 'a0 -> 'a2)) -> ('a1 -> 'a2) -> (unit -> 'a2) -> 'a0 -> 'a2 cannot be applied to parameters of types 
((soldier -> soldier -> unit) * ((soldier -> (int * int) list) -> (unit -> (int * int) list) -> soldier -> (int * int) list)), 
soldier -> soldier, 
unit -> _'a79, 
soldier, 
it doesn't match
```

Avec ces types là, ça ne marche pas en effet… `bound` est bien de type `soldier -> soldier`, mais le reste est plus embêtant à typer à la main pour voir s'il y a un problème…

J'ai par contre un souci avec le type `assoc_t`.
Si on l'écrit comme suit :
```ocaml
type setter = key -> val -> unit
type getter = (val -> 'a) -> (unit -> 'a) -> key -> 'a
type assoc_t = setter * getter
```

Ça semble convenir, mais tout est traité de la même façon (`'a` comme `key` ou `val`), or, on voudrait pouvoir changer le `'a` à la volée pour une même valeur de type `assoc_t` mais pas pouvoir changer `key` ou `val`.
Pour résumer, ne faudrait-il pas que le type soit paramétrique comme les listes ?

Bien sûr, on ne peut pas faire de type paramétrique dans notre langage, donc je comprends la notation…
Mais peut-être qu'en rendant le type checker un peu moins laxiste, je l'ai en quelque sorte obligé à fixer `key` et `val`, mais aussi `'a` du même coup…

Que faire ?

**Comment by OlivierMarty** [comment]
J'ai n'ai pas trop le temps de regarder là, mais normalement le type de getter est
```
type getter = (val -> 'a) -> (unit -> 'a) -> key -> 'a
```
Il me semble que ça marchait bien avant pour des valeurs différentes de val, key et 'a, comme les listes.

**Comment by iSheeft** [comment]
Oui pardon, mais ce n'est pas le problème.
Je pense que mon typeur était trop laxiste et que les différents alhpae n'étaient pas spécifiés.
Or, `key`, `val` et `'a` subissent le même traitement (pas de raison de faire autrement puisqu'ils sont écris de la même façon dans le code), ils sont donc spécifiés par la première utilisation (y compris `'a` !).

Il faut comprendre qu'il y a une dissymétrie implicite entre `val`-`key` et `'a` mais qu'elle n'est pas présente dans le code de l'interpréteur / typeur.

**Comment by OlivierMarty** [comment]
Pourtant les fonctions comme `list_hd` fonctionnent bien avec plusieurs types de listes, non ?

**Comment by OlivierMarty** [comment]
Ah ça y est je vois ! Le type de la map est effectivement unifié une fois pour toute... Donc il faut changer d'astuce pour les coder dans ce langage, ou augmenter un peu le langage.

**Comment by iSheeft** [comment]
Oui, mais la différence c'est que le type `'a list` est bien géré comme un type paramétrique dans le code.

Donc oui, soit on rajoute le type de `map` soit on change le type `assoc_t` pour qu'il ne parle pas de `'a`, je suis d'accord que c'est dommage parce que c'est un joli type avec des continuations.

**Comment by iSheeft** [comment]
Okay, on devrait pouvoir s'en sortir avec le type suivant :
```ocaml
type setter = key -> val -> unit
type getter = key -> val
type assoc_t = setter * getter
```

Ainsi, on peut garder `fst` pour `assoc_set` mais changer `assoc_get` pour garder son type précédent.

**Comment by OlivierMarty** [comment]
Peut-être mais assoc_get n'a pas accès à la référence qui contient la map, donc il ne saura pas s'il faut appeler le getter ou l'autre fonction.

**Comment by iSheeft** [comment]
Le problème ne se pose pas en fait. Il suffit de faire un `try with` pour agir en conséquence. Il n'y a pas besoin de la référence.
Le problème qui risque d'intervenir en revanche c'est que si quelqu'un fait `snd` sur un `assoc_t` (et ça type parce que ce n'est pas caché) il risque une exception…

**Comment by OlivierMarty** [comment]
OK, je n'étais pas sur que l'exception traverse tranquillement l'interpréteur.
Eh ben s'il fait des bêtises, sont IA meurt et puis c'est tout ! Mais c'est vrai que c'est moche :(

**Comment by iSheeft** [comment]
En fait le problème est résolu ! Cette fois-ci, le problème c'est que ta fonction `ignore` est polymorphe mais que le *type checker* ne permet pas de déduire du polymorphisme, ta fonction est donc spécialisée à sa première utilisation… (Désolé).
En attendant, je vais faire une fonction ignore spécialisée pour unit (si j'y arrive, le typeur fait encore des siennes puisqu'il type la fonction en `unit` juste… Aurais-je vraiment fait n'importe quoi avec ce code ?!).

**Comment by OlivierMarty** [comment]
OK, je sais que le polymorphisme n'est pas inféré mais en l'absence de râlement du typeur je n'avais pas vu !
Merci !

**Comment by iSheeft** [comment]
Et sinon, après le fait que

```ocaml
fun ignore () = {}
```

Soit typé en `unit` ne vient pas vraiment du *type checker*, c'est juste que le *parser* voit ça comme une abscence d'argument et pas un argument de type `unit`. Il faut donc donner un nom à la variable de type `unit`.
C'est donc réglé pour ton IA qui type et qui a l'air de bouger comme avant.
